<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo $headline ?></title>

		<link rel="stylesheet" href="//code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.min.css" />
		<link rel="stylesheet" href="/style/project.css" />

		<script src="//code.jquery.com/jquery-1.7.1.min.js" type="text/javascript"></script>
		<script src="//code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.js" type="text/javascript"></script>
		<script src="/lib/cytoscape.min.js"></script>
		<script src="/lib/arbor.js"></script>
		<script src="/lib/sylvester.js"></script>
</head>
<body>
