	<div data-role="header" data-position="fixed" data-theme="b">
	    <h1><?php echo $headline ?></h1>
	</div>

	<div data-role="content" class="osa-content">
		<h1>Create new project</h1>
		<form action="/projects/create/" method="post" id="new_project_1">
			<label for="name3" class="">Project name</label>
			<input type="text" name="name" id="name3" value="" />
			<label for="description3" class="">Description</label>
			<textarea name="description" id="description3" rows="4" ></textarea>
			<input type="submit" value="Continue" data-icon="check" />
		</form>
	</div>




