


	<div data-role="page" class="osa-demos">
		<div data-role="header" data-position="fixed" data-theme="b">
		    <h1>Aperire - Open policy optimization</h1>
		</div>
		<!-- /header -->

		<div data-role="content" class="osa-content">
			<h1><?php echo $headline ?></h1>
			<ul data-role="listview" data-count-theme="c" data-inset="true">
		<?php foreach ($projects as $project): ?>
			<li><a href="<?php echo $project->url() ?>"><?php echo $project->name ?></a></li>
		<?php endforeach;?>
			</ul>
		</div>
	</div>
		<!-- /content -->



