


	<div data-role="page" class="osa-demos">
		<div data-role="header" data-position="fixed" data-theme="c">
		    <a href="<?php echo $project_url ?>" data-icon="arrow-l">Project</a>
		    <h1><?php echo $headline ?></h1>
		</div>
		<!-- /header -->

		<div data-role="content" class="osa-content">
			<?php $formid = 'rate_form_'.rand(1,999999) ?>
			<form action="<?php echo $post_url ?>" method="post" id="<?php echo $formid ?>">
				<?php $fieldid = 'question_2_'.$questions[0]->id.'_'.$questions[1]->id?>
				<p>
				<?php echo $score ?>%
				<fieldset data-role="controlgroup">
				    <legend>How does "<?php echo $questions[0]->name?>" effect on "<?php echo $questions[1]->name?>"?</legend>
				        <input type="radio" name="<?php echo $fieldid ?>" id="<?php echo $fieldid ?>_1" value="1">
				        <label for="<?php echo $fieldid ?>_1">Is a precondition</label>
				        <input type="radio" name="<?php echo $fieldid ?>" id="<?php echo $fieldid ?>_2" value="2">
				        <label for="<?php echo $fieldid ?>_2">Facilitating</label>
				   		<input type="radio" name="<?php echo $fieldid ?>" id="<?php echo $fieldid ?>_4" value="0">
				        <label for="<?php echo $fieldid ?>_4">No effect</label>
				        <input type="radio" name="<?php echo $fieldid ?>" id="<?php echo $fieldid ?>_3" value="3">
				        <label for="<?php echo $fieldid ?>_3">Contradicts</label>

				</fieldset>
				</p>
			</form>
		</div>

<script type="text/javascript">
$("#<?php echo $formid ?> input").click(function () {
	$("#<?php echo $formid ?>").submit();
});
</script>
	<div data-role="footer" class="ui-body-c">
		<div data-role="navbar" data-position="fixed">
            <ul>
                <li><a href="<?php echo $contributors_url ?>" data-icon="star">Contributors</a></li>
                <li><a href="<?php echo $packages_url ?>" data-icon="grid">Policy packages</a></li>
                <li><a href="<?php echo $userid ? $new_tool_url : $login_url ?>" data-icon="plus">New policy</a></li>
                <li><a href="<?php echo $userid ? $rate_url : $login_url ?>" class="ui-state-persist" data-icon="check">Rare policies</a></li>

            </ul>
        </div>
	</div>
		<!-- /content -->




