<div data-role="page" class="osa-demos">
		<div data-role="header" data-position="fixed" data-theme="b">
		    <h1>Add new policy tool</h1>
		</div>
		<!-- /header -->

		<div data-role="content" class="osa-content">
			<form action="<?php echo $post_url?>" method="post">
				<label for="new_tool" class="ui-hidden-accessible">Add a policy tool:</label>
				<input type="text" name="new_tool" id="new_tool" value="" placeholder="Your great idea!" />
				<input type="submit" value="Done" data-icon="check" />
			</form>
		</div>
		<!-- /content -->

