<div data-role="page" class="osa-demos">
		<div data-role="header" data-position="fixed" data-theme="c">
			<a href="<?php echo $contributors_url ?>" data-icon="arrow-l">Project</a>
		    <h1>Add new policy tool</h1>
		</div>
		<!-- /header -->

		<div data-role="content" class="osa-content">
			<form action="<?php echo $post_url?>" method="post">
				<label for="new_tool" class="ui-hidden-accessible">Add a policy tool:</label>
				<input type="text" name="new_tool" id="new_tool" value="" placeholder="Your great idea!" />
				<input type="submit" value="Done" data-icon="check" />
			</form>
		</div>
		<!-- /content -->

	<div data-role="footer" class="ui-body-c">
		<div data-role="navbar" data-position="fixed">
            <ul>
                <li><a href="<?php echo $contributors_url ?>" data-icon="star">Contributors</a></li>
                <li><a href="<?php echo $packages_url ?>" data-icon="grid">Policy packages</a></li>
                <li><a href="<?php echo $userid ? $new_tool_url : $login_url ?>" <?php echo $userid ? 'data-rel="dialog"' : '' ?> class="ui-state-persist" data-icon="plus">New policy</a></li>
                <li><a href="<?php echo $userid ? $rate_url : $login_url ?>" data-icon="check">Rare policies</a></li>

            </ul>
        </div>
	</div>