<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">

	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<link href="apple-touch-icon.png" rel="apple-touch-icon">

	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<link href="favicon.ico" rel="icon" type="image/x-icon">
	<meta name="format-detection" content="telephone=yes">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">

	<title><?php echo $headline ?></title>

	<link rel="stylesheet" href="//code.jquery.com/mobile/1.3.1/jquery.mobile-1.3.1.min.css" />
	<link rel="stylesheet" href="/style/project.css" />

	<script src="//code.jquery.com/jquery-1.7.1.min.js" type="text/javascript"></script>
	<script src="//code.jquery.com/mobile/1.3.0/jquery.mobile-1.3.0.js" type="text/javascript"></script>
	<script src="/lib/cytoscape.min.js"></script>
	<script src="/lib/arbor.js"></script>
	<script src="/lib/sylvester.js"></script>
</head>
<body>
<div data-role="page" class="osa-demos">
