	<div data-role="header" data-position="fixed" data-theme="b">
		<a href="<?php echo $packages_url ?>" data-icon="back">Done</a>
	    <h1>Add new policy tool</h1>
	</div>
	<!-- /header -->

	<div data-role="content" class="osa-content">
		<p>Every project is made out of policies. Policies are principles or rules to guide decisions and achieve rational outcomes.<br />
		Write a short name that will explain what it is about and use the explanation field to extend it.</p>
		<form action="<?php echo $post_url?>" method="post">
			<label for="name4" class="ui-hidden-accessible">Add a policy tool:</label>
			<input type="text" name="name" id="name4" value="" placeholder="Policy name" />
			<label for="description4" class="ui-hidden-accessible">Explanation:</label>
			<textarea cols="40" rows="8" name="description" id="description4" placeholder="Explanation"></textarea>
			<input type="submit" value="Done" data-icon="check" />
		</form>
		<ul data-role="listview" data-count-theme="c" data-inset="true">
		<?php foreach ($tools as $tool) :?>
			    <li><?php echo $tool->name ?></li>
		<?php endforeach;?>
		</ul>
	</div>
		<!-- /content -->
